In [2]:
import numpy as np

# Mathematics

Arithmetic, Trigonometry

In [2]:
# Creating a 1d array
a = np.array([1,2,3,4])

In [5]:
# Increasing each element in a by 2
a + 2

array([3, 4, 5, 6])

In [4]:
# Multiplying each element in a by 2
a * 2

array([2, 4, 6, 8])

In [6]:
# Creatig array b and then adding a+b
b = np.array([1,2,3,4])
a+b

array([2, 4, 6, 8])

In [7]:
# Finding the sin values of a
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

Linear Algebra

In [12]:
# multiply matrix c with d
c = np.ones((2,3))
print(c)
d = np.full((3,2), 2)
print(d)

np.matmul(c,d)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [15]:
# Finding determinant of a 3 x 3 identity matrix
e = np.identity(3)
np.linalg.det(e)

1.0

Statistics

In [18]:
# Creating a 2d array
stats = np.array([[1,2,3], [4,5,6]])

In [19]:
# Finding the smallest element in array stats
np.min(stats)

1

In [24]:
# Finding the smallest element horizontally
np.min(stats, axis = 1)

array([1, 4])

This looks at the minimum value from each row. It selects 1 as minimum from [1,2,3] and 4 as minimum from [4,5,6]

In [23]:
# Finding the smallest element vertically
np.min(stats, axis = 0)

array([1, 2, 3])

This looks at minimum value from each column

[1 , 2 , 3]

[4 , 5 , 6]

1 < 4 , 2 < 5, 3 < 6

# Reorganizing Arrays

In [32]:
# Reshaping a 2 x 4 array
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print()

after1 = before.reshape((4,2))
print(after1)
print()

after2 = before.reshape((2,2,2))
print(after2)

[[1 2 3 4]
 [5 6 7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Note: To reshape, the before and after matrices should be of the same size. before, after1 and after2 are all of size 8

In [34]:
# Vertical stacking
a1 = np.array([1,2,3])
a2 = np.array([2,3,4])

np.vstack([a1,a2])

array([[1, 2, 3],
       [2, 3, 4]])

In [35]:
# Horizontal stacking
np.hstack([a1,a2])

array([1, 2, 3, 2, 3, 4])

Practice Exercises

In [4]:
mat = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(mat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
# Get only the last two rows


In [7]:
# Find the sum of all its elements 
sum = mat.sum()
print(sum)

78


In [11]:
# Find the sum of only the first row
sum_row1 = mat[0].sum()
print(sum_row1)

10


In [12]:
# Find the sum of each row
sum_rows = mat.sum(axis=0)
print(sum_rows)

[15 18 21 24]
