In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [8]:
b = np.full((3,1),2)

In [9]:
b

array([[2],
       [2],
       [2]])

In [10]:
np.matmul(a,b)

array([12])

#### Statistics
Let me write a line of notes



In [29]:
stats = np.array([[1,2,3], [4,5,6],[7,8,9]])
stats

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
np.min(stats, axis =0)

array([1, 2, 3])

In [31]:
np.min(stats, axis =1)

array([1, 4, 7])

In [32]:
np.min(stats)

1

In [34]:
np.max(stats, axis=0)

array([7, 8, 9])

In [35]:
np.max(stats, axis = 1)

array([3, 6, 9])

In [36]:
np.sum(stats, axis =0)

array([12, 15, 18])

In [37]:
np.sum(stats, axis = 1)

array([ 6, 15, 24])

In [47]:
before = np.array([[1,2,3],[4,5,6]])
print(before)

after = before.reshape((2,1,3))
print(after)

[[1 2 3]
 [4 5 6]]
[[[1 2 3]]

 [[4 5 6]]]


In [57]:
v1 = np.array((1,2))
v2 = np.array((3,4)


v4 =np.hstack((v1,v2))
print(v4)

SyntaxError: invalid syntax (<ipython-input-57-554e14457141>, line 5)

In [4]:
id = np.identity(4)
print(id)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [6]:
row0 = id[0]
print(row0)

[1. 0. 0. 0.]


In [8]:
row_last2 = id[2:]
print(row_last2)

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
id[2,0] = 2
print(id)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [2. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
row_first_column = id[0, :]
print(row_first_column)

[1. 0. 0. 0.]


In [21]:
print(id[:, 1:])

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
print(id[: , [0,3]])

[[1. 0.]
 [0. 0.]
 [2. 0.]
 [0. 1.]]
