In [8]:
import numpy as np

# Making arrays

In [9]:
# Making a single dimensional array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [10]:
# Making a 2 dimensional array
b = np.array([[2,3,4],[5,6,7]])
print(b)

[[2 3 4]
 [5 6 7]]


In [11]:
# Making a 3 dimesional array
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Practice!

In [12]:
# Make a one dimensional array with only even numbers


In [13]:
# Make a two dimensional array with only prime numbers


In [14]:
# Make a three dimensional array with only composite numbers


# Dimensions

In [15]:
# Get dimension of a
a.ndim

1

In [16]:
# Get dimension of b
b.ndim

2

In [17]:
# Get dimension of c
c.ndim

3

# Shapes
Basically shows you the number of rows and columns.  For a one dimesional array, it only shows the columns.

In [18]:
# Get shape of a
a.shape

(3,)

In [19]:
# Get shape of b
b.shape

(2, 3)

In [20]:
# Get shape of c
c.shape

# c has 2 rows done twice

(2, 2, 3)

# Datatype
The default is datatype is based on your computer. If your PC is 32 bit then your default datatype is int32. If your PC is 64 bit your default datatype is int64. These are the defaults unless specified otherwise by the user

Additionally, floats are bigger than integers and take up more space

In [21]:
# get the datatype for a
a.dtype

dtype('int32')

In [22]:
# get the datatype for z
z = np.array([5,4,3], dtype = 'int8')
z.dtype

dtype('int8')

In [23]:
# Get datatype for y
y = np.array([1.0,2.0,3.0])
y.dtype

dtype('float64')

# Size
rows * columns

In [24]:
# Get the size for a
a.size

3

In [25]:
# Get the size for b
b.size

6

3 dim arrays size = rows * rows * columnns

In [26]:
# Get the size for c
c.size

12

# Itemsize

8 bits = 1 byte

32 bits = 4 bytes

64 bits = 8 bytes

In [27]:
# Get itemsize for a
a.itemsize

4

The default datatype  for a is int32. So 32 bits = 4 bytes

In [28]:
# Get itemsize for b
b.itemsize

4

Same default datatype as a

In [29]:
# Get itemsize for z
z.itemsize

1

We specified z to have dtype int8. So 8 bits = 1 byte

# Nbytes

size * itemsize

It gives the total bytes consumed by the elements of the array

In [30]:
# Get number of bytes of a
a.nbytes

12

In [31]:
# Get number of bytes of b
b.nbytes

24

In [32]:
# Get number of bytes of c
c.nbytes

48

In [33]:
# Get number of bytes of z
z.nbytes

3

# Accessing/Changing elements in rows, columns

In [34]:
# Consider a 2 dim matrix
x = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(x)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [35]:
# access the element 13 from x
x[1,5]

13

Why [1,5] ?

x has two rows:

[1,2,3,4,5,6,7] Since this is the first row. It is indicated as 0. NOT 1!

[8,9,10,11,12,13,14] Sice this is the second row, it is indicated as 1.

-----------------------------------------------------------------------------

Similarly, for the columns, the first element in the columns is indicated as 0

[1,2,3,4,5,6,7] = 0,1,2,3,4,5,6

[8,8,10,11,12,13,14] = 0,1,2,3,4,5,6

-----------------------------------------------------------------------------
To find 13, we go [row of 13, column of 13]

13 is in the second row which is indicated as 1

13 is in the sixth column indicated as 5

---------------------------------------------------------------------------
Therefore we have x[1,5]

In [36]:
# access element 13 from x using negative notation
x[-1,-2]

13

-1 is the last column, -2 is the second to last element

In [37]:
# Get everything from the first row
x[0, :]

array([1, 2, 3, 4, 5, 6, 7])

This is actually x[0, start:stop]

Since there is no starting point or ending point, it gives you everything from the first column 0

In [38]:
# Get the sixth column from each row
x[:, 5]

array([ 6, 13])

In [39]:
# Get the odd elements from the fist row
x[0, 0:6:2]

array([1, 3, 5])

0:6:2 = start:stop:step (step 2 being jump 2 characters)

In [40]:
# Get even elements from the second row
x[1, 0:6:2]

array([ 8, 10, 12])

Practice!

In [41]:
# Get everything from the second row


In [42]:
# Get even elements from the first row


In [43]:
# Get odd elements from the second row


In [1]:
# Get the first five elements from each row
