In [2]:
import numpy as np

# Accessing/Changing elements in rows, columns# Accessing/Changing elements in rows, columns

In [11]:
# Making an 2 dimensional array with prime numbers
y = np.array([[1,3,5,7,11], [13,17,19,23,29]])
print(y)

[[ 1  3  5  7 11]
 [13 17 19 23 29]]


In [12]:
# Replacing the third element of the second row with a composite number
y[1,2] = 9
print(y)

[[ 1  3  5  7 11]
 [13 17  9 23 29]]


In [13]:
# Replacing the fourth element of each row with even numbers
y[: , 3] = [2,4]
print(y)

[[ 1  3  5  2 11]
 [13 17  9  4 29]]


Practice!

In [14]:
# Replace the last element of the first row with an odd number


In [15]:
# Replace the last element of each row with even numbers


In [17]:
# Creating a 3d array
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
# Retrieve 5
a[1,0,0]

5

In [19]:
# Retrieve [[3,4], [7,8]]
a[:, 1, :]

array([[3, 4],
       [7, 8]])

In [20]:
# Replace [[3,4], [7,8]] by [[9,9], [8,8]]
a[ :, 1, : ] = [[9,9],[8,8]]
print(a)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


Practice!

In [23]:
# Retrieve [1,2]


In [48]:
# Retrieve [[1,2], [5,6]]


In [49]:
# Replace  [[1,2],[5,6]] by [[11,22],[55,66]]


# Initializing arrays

In [50]:
# Making a single dimensional array with 4 elements
np.zeros(4)

array([0., 0., 0., 0.])

In [53]:
# Making a 3 simensional array with pnes
np.ones((2,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [54]:
# Make a 3 dimensional array with all elemnets as 10
np.full((2,2,2), 10)

array([[[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]]])

When using full_like, it copies the dimensions of the existing array

In [55]:
# Copy the dimensions of a and fill it with the number 7
np.full_like(a, 7)

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [56]:
# Create a 2 dimensional array with random decimals
np.random.rand(2,2)

array([[0.68143624, 0.99501454],
       [0.76702607, 0.15731494]])

In [59]:
# Create a 2 dimensional arrays with random integers where numbers generates are not greater than 4
np.random.randint(4,size= (2,2))

array([[2, 1],
       [2, 3]])

In [68]:
# Create an identity matrix with 4 columns and 4 rows
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [81]:
# repeating an array
b = np.array([1,2,3])
rpt = np.repeat(b,3)
print(rpt)

[1 1 1 2 2 2 3 3 3]


By default, rpt = np.repeat(b,3, axis = 1). 

If we want to repeat vertically, it has to be a 2 dimensional matrix

Horizontally : axis = 1,

Vertically : axis = 0


In [80]:
# repeating an array vertically
c = np.array([[1,2,3]])
rpt2 = np.repeat(c,3, axis = 0)
print(rpt2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


Practice!


Create this matrix:

[[1,1,1,1,1]

  [1,0,0,0,1]
 
  [1,0,9,0,1]
 
  [1,0,0,0,1]
 
  [1,1,1,1,1,]]

In [82]:
g = np.ones((5,5))

In [83]:
g[1:4, 1:4] = 0
print(g)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [84]:
g[2,2] = 9
print(g)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
